// =============================================================================
// auth-middleware.ts — src/integrations/supabase/auth-middleware.ts
// =============================================================================
// A TanStack Start server middleware that verifies a Supabase JWT from the
// incoming HTTP request's Authorization header and passes the authenticated
// user's ID and claims downstream to server functions.
//
// How it works:
// 1. Reads the `Authorization: Bearer <token>` header from the request.
// 2. Creates a per-request Supabase client with the token attached (so any
//    subsequent DB queries run with that user's identity and obey RLS policies).
// 3. Validates the token using `getClaims` — this extracts the JWT claims
//    without making a network call to Supabase Auth.
// 4. Makes `supabase`, `userId`, and `claims` available to the next handler.
//
// Usage in a server function:
//   import { requireSupabaseAuth } from "@/integrations/supabase/auth-middleware";
//   const myFn = createServerFn()
//     .middleware([requireSupabaseAuth])
//     .handler(async ({ context }) => {
//       const { userId } = context; // type-safe, already verified
//     });
//
// KEYWORDS: AUTH, MIDDLEWARE
// =============================================================================

// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from "@tanstack/react-start";
import { getRequest } from "@tanstack/react-start/server";
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

/**
 * TanStack Start server middleware that enforces Supabase authentication.
 * Add this to any server function that requires a logged-in user.
 *
 * AUTH: validates the JWT from the Authorization header.
 * If validation fails for any reason, throws a 401 Response to reject the request.
 * On success, passes `supabase`, `userId`, and `claims` into the handler's context.
 *
 * The per-request Supabase client is configured with the user's JWT so all
 * database queries run with that user's RLS policies applied — you get the
 * security benefits of RLS without manually checking ownership in every handler.
 */
export const requireSupabaseAuth = createMiddleware({ type: "function" }).server(
  async ({ next }) => {
    const SUPABASE_URL = process.env.SUPABASE_URL;
    const SUPABASE_PUBLISHABLE_KEY = process.env.SUPABASE_PUBLISHABLE_KEY;

    // VALIDATION: ensure the required environment variables are present before proceeding
    if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
      const missing = [
        ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
        ...(!SUPABASE_PUBLISHABLE_KEY ? ["SUPABASE_PUBLISHABLE_KEY"] : []),
      ];
      const message = `Missing Supabase environment variable(s): ${missing.join(", ")}. Connect Supabase in Lovable Cloud.`;
      console.error(`[Supabase] ${message}`);
      throw new Response(message, { status: 500 });
    }

    // Get the current HTTP request object from TanStack Start's server context
    const request = getRequest();

    if (!request?.headers) {
      throw new Response("Unauthorized: No request headers available", { status: 401 });
    }

    // AUTH: Read the Authorization header — expected format: "Bearer <jwt>"
    const authHeader = request.headers.get("authorization");

    if (!authHeader) {
      throw new Response("Unauthorized: No authorization header provided", { status: 401 });
    }

    // AUTH: Only Bearer tokens are supported — reject Basic auth or other schemes
    if (!authHeader.startsWith("Bearer ")) {
      throw new Response("Unauthorized: Only Bearer tokens are supported", { status: 401 });
    }

    // Strip the "Bearer " prefix to get the raw JWT string
    const token = authHeader.replace("Bearer ", "");
    if (!token) {
      throw new Response("Unauthorized: No token provided", { status: 401 });
    }

    // Create a per-request Supabase client with the user's token attached.
    // This means any DB query made with this client will run under the user's
    // identity and be subject to RLS policies (unlike the service-role client).
    const supabase = createClient<Database>(SUPABASE_URL!, SUPABASE_PUBLISHABLE_KEY!, {
      global: {
        headers: {
          Authorization: `Bearer ${token}`,
        },
      },
      auth: {
        storage: undefined,      // Server context — no browser storage
        persistSession: false,   // Each request is independent
        autoRefreshToken: false, // Server doesn't need to auto-refresh
      },
    });

    // AUTH: Verify the JWT by extracting its claims without a network round-trip.
    // getClaims parses the JWT locally and checks its signature and expiry.
    const { data, error } = await supabase.auth.getClaims(token);
    if (error || !data?.claims) {
      throw new Response("Unauthorized: Invalid token", { status: 401 });
    }

    // AUTH: The `sub` claim is the user's UUID — it must be present for a valid user token
    if (!data.claims.sub) {
      throw new Response("Unauthorized: No user ID found in token", { status: 401 });
    }

    // Pass the verified user context downstream to the server function handler
    return next({
      context: {
        supabase,               // User-scoped Supabase client (respects RLS)
        userId: data.claims.sub, // The authenticated user's UUID
        claims: data.claims,    // Full JWT claims (roles, metadata, etc.)
      },
    });
  },
);
