// =============================================================================
// client.ts — src/integrations/supabase/client.ts
// =============================================================================
// The browser-side Supabase client used by all frontend code (components, hooks,
// lib files). This is a lazily-initialised singleton — the actual client object
// is not created until the first time a property is accessed (via a JS Proxy).
//
// This lazy approach prevents the client from being constructed at module-load
// time, which would throw if the environment variables aren't available yet
// (e.g., during server-side rendering in some frameworks).
//
// Import pattern: import { supabase } from "@/integrations/supabase/client";
//
// SECURITY: This uses the PUBLISHABLE (anon) key — it is safe to include in
// browser bundles. Supabase Row-Level Security (RLS) policies on the database
// restrict what an anon-key client can actually read or write.
//
// KEYWORDS: DATABASE, AUTH
// =============================================================================

// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

/**
 * Internal factory that creates and configures the Supabase client.
 * Called at most once, the first time `supabase` is accessed.
 *
 * Reads environment variables from Vite's import.meta.env (build-time replacement)
 * with a fallback to process.env for SSR environments.
 *
 * Auth configuration:
 * - `storage: localStorage` — persists the session in the browser across page reloads
 * - `persistSession: true` — writes the session to storage
 * - `autoRefreshToken: true` — silently refreshes JWTs before they expire
 */
function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL =
    import.meta.env.VITE_SUPABASE_URL ??
    (typeof process !== "undefined" ? process.env.SUPABASE_URL : undefined);
  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ??
    (typeof process !== "undefined" ? process.env.SUPABASE_PUBLISHABLE_KEY : undefined);

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ["SUPABASE_PUBLISHABLE_KEY"] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(", ")}. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      // Use sessionStorage so the token is cleared when the browser/tab closes
      // and is not permanently visible in Application → Local Storage
      storage: typeof window !== "undefined" ? sessionStorage : undefined,
      persistSession: true,
      // Automatically refresh the JWT before it expires (every ~55 minutes)
      autoRefreshToken: true,
    },
  });
}

// The real client is stored here once created. `undefined` until first access.
let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

/**
 * The browser-side Supabase client, exposed as a Proxy for lazy initialisation.
 *
 * WHY a Proxy: importing this module doesn't immediately call createSupabaseClient().
 * The first time you actually use `supabase.from(...)` or `supabase.auth.getUser()`
 * the Proxy's `get` trap intercepts the property access, creates the real client
 * if it doesn't exist yet, and forwards the property access to it.
 *
 * This means if env vars are missing, the error is thrown at the moment you
 * first use the client — which gives a much clearer stack trace than a
 * module-load-time error.
 */
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    // Lazily create the client on first property access
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
