// =============================================================================
// client.server.ts — src/integrations/supabase/client.server.ts
// =============================================================================
// Server-side Supabase client that uses the SERVICE ROLE key instead of the
// anon/publishable key. The service role key bypasses ALL Row-Level Security
// (RLS) policies — meaning this client can read and write ANY row in the database
// regardless of which user is making the request.
//
// SECURITY WARNING: Never import this file in client-side (browser) code.
// Only use it in server functions, API routes, or trusted backend services.
// Exposing the service role key in a browser bundle would let anyone bypass
// your database security policies.
//
// Use the regular `client.ts` for user-authenticated queries with RLS.
// Use the `auth-middleware.ts` to get a user-scoped client in server functions.
//
// Import pattern: import { supabaseAdmin } from "@/integrations/supabase/client.server";
//
// KEYWORDS: DATABASE, AUTH
// =============================================================================

// This file is automatically generated. Do not edit it directly.
// Server-side Supabase client with service role key - bypasses RLS.
// Use this for admin operations in server functions and server routes only.
// For user-authenticated queries (with RLS), use the auth middleware instead.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

/**
 * Internal factory that creates the admin Supabase client.
 * Uses process.env (not import.meta.env) because this code only runs on the server.
 *
 * Auth configuration differences from the browser client:
 * - `storage: undefined` — no session storage needed; server has no browser storage
 * - `persistSession: false` — no session persistence for server-side requests
 * - `autoRefreshToken: false` — service role keys don't expire; no refresh needed
 */
function createSupabaseAdminClient() {
  const SUPABASE_URL = process.env.SUPABASE_URL;
  const SUPABASE_SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_SERVICE_ROLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
      ...(!SUPABASE_SERVICE_ROLE_KEY ? ["SUPABASE_SERVICE_ROLE_KEY"] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(", ")}. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, {
    auth: {
      storage: undefined,      // No browser storage on the server
      persistSession: false,   // Each server request is stateless
      autoRefreshToken: false, // Service role keys don't expire
    },
  });
}

// The real admin client is stored here once created. `undefined` until first access.
let _supabaseAdmin: ReturnType<typeof createSupabaseAdminClient> | undefined;

// Server-side Supabase client with service role - bypasses RLS
// SECURITY: Only use this for trusted server-side operations, never expose to client code
// Import like: import { supabaseAdmin } from "@/integrations/supabase/client.server";

/**
 * The server-side admin Supabase client, lazily initialised via a Proxy.
 * SECURITY: Only use this for trusted server-side operations.
 *
 * Same lazy Proxy pattern as client.ts — the real client is not created until
 * the first property access. This prevents errors during module loading when
 * environment variables might not yet be available.
 */
export const supabaseAdmin = new Proxy({} as ReturnType<typeof createSupabaseAdminClient>, {
  get(_, prop, receiver) {
    // Lazily create the admin client on first property access
    if (!_supabaseAdmin) _supabaseAdmin = createSupabaseAdminClient();
    return Reflect.get(_supabaseAdmin, prop, receiver);
  },
});
